export const READING_LIST_REQUEST = 'READING_LIST_REQUEST';
export const READING_LIST_REQUEST_SUCCESS = 'READING_LIST_REQUEST_SUCCESS';
export const READING_LIST_REQUEST_FAILED = 'READING_LIST_REQUEST_FAILED';

